#!/usr/bin/env bash
# Regenerate the bundled vendor brand icons (MADR 0082 D5).
#
# Inputs, both committed next to this script:
#   ids.txt   — one upstream id per line: the union of the goose pinned table
#               (internal/provider/goose/catalog.go), a live opencode/kilo
#               catalog dump, and the five agent ids. Grows by hand when a
#               catalog gains vendors worth a real logo; anything missing
#               renders as a monogram, so staleness is cosmetic.
#   map.json  — id → Lobe Icons slug overrides for names that differ.
#
# Output:
#   apps/mobile/assets/vendor_icons/<slug>.svg      (monochrome, deduplicated)
#   apps/mobile/lib/features/widgets/vendor_icon_manifest.g.dart
#
# The manifest is a const Dart map so lookup is compile-time — no runtime IO,
# no AssetManifest probing. Icons come from @lobehub/icons-static-svg (MIT),
# pinned below; monochrome variants only, so they tint with the theme.
set -euo pipefail

LOBE_ICONS_VERSION=1.94.0

HERE="$(cd "$(dirname "$0")" && pwd)"
REPO="$(cd "$HERE/../.." && pwd)"
ASSETS="$REPO/apps/mobile/assets/vendor_icons"
MANIFEST="$REPO/apps/mobile/lib/features/widgets/vendor_icon_manifest.g.dart"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

echo "fetching @lobehub/icons-static-svg@${LOBE_ICONS_VERSION}…"
curl -fsSL -o "$TMP/pkg.tgz" \
  "https://registry.npmjs.org/@lobehub/icons-static-svg/-/icons-static-svg-${LOBE_ICONS_VERSION}.tgz"
tar -xzf "$TMP/pkg.tgz" -C "$TMP"

rm -rf "$ASSETS"
mkdir -p "$ASSETS"

python3 - "$HERE" "$TMP/package/icons" "$ASSETS" "$MANIFEST" "$LOBE_ICONS_VERSION" <<'PY'
import json, os, shutil, sys

here, icons, assets, manifest, version = sys.argv[1:6]

# Monochrome base variants only: `<slug>.svg`, skipping -color/-text/-brand.
def is_base(f):
    if not f.endswith('.svg'):
        return False
    slug = f[:-4]
    return not any(slug.endswith(s) for s in ('-color', '-text', '-brand', '-brand-color'))

available = {f[:-4] for f in os.listdir(icons) if is_base(f)}

ids = [l.strip() for l in open(os.path.join(here, 'ids.txt')) if l.strip()]
overrides = {
    k: v for k, v in json.load(open(os.path.join(here, 'map.json'))).items()
    if not k.startswith('_')
}

def resolve(i):
    if i in overrides:
        return overrides[i] if overrides[i] in available else None
    for c in (i, i.replace('_', '').replace('-', ''), i.replace('_', '-')):
        if c in available:
            return c
    return None

mapping, unmatched = {}, []
for i in sorted(set(ids)):
    slug = resolve(i)
    if slug is None:
        unmatched.append(i)
    else:
        mapping[i] = slug

for slug in sorted(set(mapping.values())):
    shutil.copyfile(os.path.join(icons, slug + '.svg'),
                    os.path.join(assets, slug + '.svg'))

with open(manifest, 'w') as f:
    f.write('// GENERATED by tools/vendor-icons/sync.sh — do not edit.\n')
    f.write(f'// Source: @lobehub/icons-static-svg {version} (MIT).\n')
    f.write(f'// {len(mapping)} of {len(set(ids))} known upstream ids have a brand icon;\n')
    f.write('// the rest render as monograms (MADR 0082 D5).\n\n')
    f.write('const Map<String, String> kVendorIconAssets = {\n')
    for i in sorted(mapping):
        f.write(f"  '{i}': 'assets/vendor_icons/{mapping[i]}.svg',\n")
    f.write('};\n')

print(f"matched {len(mapping)} ids -> {len(set(mapping.values()))} icons; "
      f"{len(unmatched)} ids fall back to monograms")
PY

if command -v dart >/dev/null 2>&1; then
  dart format "$MANIFEST" >/dev/null
fi

size_kb="$(du -sk "$ASSETS" | cut -f1)"
echo "vendor icons: ${size_kb} KB in $ASSETS"
if [ "$size_kb" -gt 400 ]; then
  echo "error: asset set exceeds the 400 KB budget (MADR 0082)" >&2
  exit 1
fi
