package codex

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

// TestGenerateContractManifest is an explicit, deterministic fixture
// generator. Ordinary test runs skip it; P1/P17 invoke it against temporary
// schema trees generated by the exact Codex binary and the separately pinned
// source exports.
func TestGenerateContractManifest(t *testing.T) {
	if os.Getenv("CODEX_CONTRACT_GENERATE") != "1" {
		t.Skip("set CODEX_CONTRACT_GENERATE=1 to refresh exact-version fixtures")
	}
	in := readGeneratorInputs(t)

	stable, stableDocs := readGeneratedSurface(t, in.installedStable)
	experimental, experimentalDocs := readGeneratedSurface(t, in.installedExpUnfl)

	// Report the real notification stability split, but do NOT rewrite the
	// captured surface with it (MADR 0163 D4, partially deferred).
	//
	// Codex's exporter never prunes experimental notifications, so both bundles
	// list all 82 while the runtime suppresses 22 of them. The honest fix is to
	// record the split as its own field, and that is a manifest SCHEMA change:
	// Validate pins schema_version to 1, and MADR 0135 requires a schema change to
	// bump the manifest version. Filtering the stable surface in place instead
	// makes the manifest disagree with the exporter it claims to mirror, which
	// breaks the drift gate's exact mode — measured, not theorised.
	//
	// So the capture stays faithful to the exporter, the split is reported here and
	// documented in the README, and persisting it waits for schema_version 2.
	experimentalOnly := experimentalNotifications(t, in.sourceTree)
	total := len(experimental.ServerNotifications)
	stableOnly := len(stableNotificationsOnly(stable.ServerNotifications, experimentalOnly))
	t.Logf("notifications: %d declared; %d stable, %d experimental-only by the source markers "+
		"(the captured surface records all %d, as the exporter emits them)",
		total, stableOnly, total-stableOnly, total)

	manifest := ContractManifest{
		SchemaVersion: 1,
		CodexVersion:  in.version,
		BinarySHA256:  in.binarySHA256,
		Stable:        stable,
		Experimental:  experimental,
	}
	manifest.Capabilities = generatedCapabilities(stable, experimental)
	manifest.Fixtures = generatedFixtures(stable, experimental, stableDocs, experimentalDocs)
	if err := manifest.Validate(); err != nil {
		t.Fatalf("generated manifest: %v", err)
	}

	sourceStableSurface, _ := readGeneratedSurface(t, in.sourceStable)
	sourceExperimentalSurface, _ := readGeneratedSurface(t, in.sourceExp)
	watch := SourceWatchManifest{
		SchemaVersion:  1,
		Commit:         in.sourceCommit,
		Stable:         sourceStableSurface,
		Experimental:   sourceExperimentalSurface,
		InstalledDelta: sourceOnlyDelta(stable, experimental, sourceStableSurface, sourceExperimentalSurface),
	}

	fixtures := manifest.Fixtures
	manifest.Fixtures = nil
	if err := os.MkdirAll(in.outDir, 0o755); err != nil {
		t.Fatal(err)
	}
	writeGeneratedJSON(t, filepath.Join(in.outDir, "manifest.json"), manifest)
	writeGeneratedJSON(t, filepath.Join(in.outDir, "fixtures.json"), fixtures)
	writeGeneratedJSON(t, filepath.Join(in.outDir, "source-watch-manifest.json"), watch)
}

type generatedSchemaDocs struct {
	definitions map[string]struct {
		Required []string `json:"required"`
	}
}

func readGeneratedSurface(t *testing.T, schemaPath string) (ContractSurface, generatedSchemaDocs) {
	t.Helper()
	raw, err := os.ReadFile(schemaPath)
	if err != nil {
		t.Fatal(err)
	}
	requests, err := parseSchemaMethods(raw, "ClientRequest")
	if err != nil {
		t.Fatal(err)
	}
	notifications, err := parseSchemaMethods(raw, "ServerNotification")
	if err != nil {
		t.Fatal(err)
	}
	callbackRaw := raw
	if _, err := parseSchemaMethods(callbackRaw, "ServerRequest"); err != nil {
		callbackRaw, err = os.ReadFile(filepath.Join(filepath.Dir(schemaPath), "ServerRequest.json"))
		if err != nil {
			t.Fatalf("read ServerRequest schema beside %s: %v", schemaPath, err)
		}
	}
	callbacks, err := parseSchemaMethods(callbackRaw, "ServerRequest")
	if err != nil {
		t.Fatal(err)
	}
	var parsed struct {
		Definitions map[string]struct {
			Required []string `json:"required"`
		} `json:"definitions"`
	}
	if err := json.Unmarshal(raw, &parsed); err != nil {
		t.Fatal(err)
	}
	for name, definition := range readStandaloneSchemas(t, filepath.Dir(schemaPath)) {
		if _, exists := parsed.Definitions[name]; !exists {
			parsed.Definitions[name] = definition
		}
	}
	classifyGenerated(t, requests, WireClientRequest)
	classifyGenerated(t, notifications, WireNotification)
	classifyGenerated(t, callbacks, WireServerRequest)
	return ContractSurface{
		ClientRequests: requests, ServerNotifications: notifications, ServerRequests: callbacks,
	}, generatedSchemaDocs{definitions: parsed.Definitions}
}

// classifyGenerated marks each captured method with what this package does about
// it, derived from the package's own code (MADR 0163 D2) rather than from the
// hand-maintained switch this replaces. That switch named 32 client requests and
// zero server requests, so every one of the 21 server requests was recorded as
// typed_deferred while session.go answered nine of them on purpose (0163 F5), and
// the list drifted from the code silently because nothing compared the two.
func classifyGenerated(t *testing.T, entries []WireContract, kind WireKind) {
	t.Helper()
	callArgs, caseLabels := implementedMethods(t)
	for i := range entries {
		method := entries[i].Method
		entries[i].Classification = ClassificationTypedDeferred
		if kind == WireNotification {
			entries[i].Response = "none"
		} else {
			entries[i].Response = "typed"
		}
		switch {
		case method == "initialize" || method == "initialized":
			entries[i].Classification = ClassificationInternal
		case kind == WireNotification:
			// The routing decision itself, so it cannot disagree with runtime
			// behaviour the way a parallel list can.
			if notificationRouteFor(method) != notificationRouteUnknown {
				entries[i].Classification = ClassificationImplemented
			}
		case kind == WireServerRequest:
			if _, ok := caseLabels[method]; ok {
				entries[i].Classification = ClassificationImplemented
			}
		default:
			if _, ok := callArgs[method]; ok {
				entries[i].Classification = ClassificationImplemented
			}
		}
	}
}

func generatedCapabilities(stable, experimental ContractSurface) []CapabilityContract {
	// exposed lists the methods we choose to offer as capabilities. It carries no
	// stability claim of its own: stability is derived from the schema bundles
	// below. A hand-maintained stability list goes on calling a method
	// experimental long after upstream promotes it, which is exactly what happened
	// to thread/items/list and thread/turns/list — stable since #40673, still
	// emitted here as experimental with a fallback to the deprecated thread/read
	// (MADR 0163, amendment 2026-09-21).
	//
	// The split below is kept only because the two groups read differently to a
	// human; both halves land in the same map.
	exposed := map[string]SecurityClass{}
	for _, method := range []string{
		"initialize", "thread/list", "thread/read", "thread/loaded/list", "thread/start", "thread/resume", "thread/fork",
		"thread/name/set", "thread/metadata/update", "thread/section/move", "thread/archive", "thread/unarchive",
		"thread/unsubscribe", "thread/delete", "threadSection/list", "threadSection/create", "threadSection/update", "threadSection/delete",
		"turn/start", "turn/steer", "turn/interrupt", "thread/shellCommand", "command/exec", "command/exec/write",
		"command/exec/resize", "command/exec/terminate", "review/start", "thread/compact/start", "thread/approveGuardianDeniedAction",
		"thread/goal/set", "thread/goal/get", "thread/goal/clear", "model/list", "modelProvider/capabilities/read",
		"permissionProfile/list", "experimentalFeature/list", "experimentalFeature/enablement/set", "config/read", "config/value/write",
		"config/batchWrite", "configRequirements/read", "skills/list", "skills/extraRoots/set", "skills/config/write", "hooks/list",
		"app/list", "app/read", "app/installed", "marketplace/add", "marketplace/remove", "marketplace/upgrade", "plugin/list",
		"plugin/installed", "plugin/read", "plugin/skill/read", "plugin/install", "plugin/uninstall", "plugin/share/save",
		"plugin/share/updateTargets", "plugin/share/list", "plugin/share/checkout", "plugin/share/delete", "mcpServerStatus/list",
		"mcpServer/oauth/login", "config/mcpServer/reload", "mcpServer/resource/read", "mcpServer/tool/call", "fs/getMetadata",
		"fs/readDirectory", "fs/readFile", "fs/writeFile", "fs/createDirectory", "fs/copy", "fs/remove", "fs/watch", "fs/unwatch",
		"fuzzyFileSearch", "account/read", "account/login/start", "account/login/cancel", "account/logout", "account/rateLimits/read",
		"account/usage/read", "account/workspaceMessages/read", "account/rateLimitResetCredit/consume", "account/sendAddCreditsNudgeEmail",
		"externalAgentConfig/detect", "externalAgentConfig/import", "externalAgentConfig/import/recordHistory",
		"externalAgentConfig/import/readHistories", "feedback/upload",
	} {
		exposed[method] = securityForMethod(method)
	}
	for _, method := range []string{
		"server/diagnostics", "thread/search", "thread/searchOccurrences", "thread/turns/list", "thread/items/list",
		"thread/settings/update", "thread/queue/add", "thread/queue/list", "thread/queue/update", "thread/queue/delete",
		"thread/queue/reorder", "thread/queue/start", "thread/backgroundTerminals/clean", "thread/backgroundTerminals/list",
		"thread/backgroundTerminals/terminate", "thread/realtime/start", "thread/realtime/appendAudio", "thread/realtime/appendText",
		"thread/realtime/appendSpeech", "thread/realtime/stop", "thread/realtime/listVoices", "fuzzyFileSearch/sessionStart",
		"fuzzyFileSearch/sessionUpdate", "fuzzyFileSearch/sessionStop", "plugin/search", "collaborationMode/list",
		"project/list", "project/read", "project/create", "project/import", "project/update", "project/move", "project/delete",
		"environment/add", "environment/status", "environment/info", "process/spawn", "process/writeStdin", "process/resizePty", "process/kill",
	} {
		exposed[method] = securityForMethod(method)
	}

	// Stability is a property of the engine's schema, not of our opinion: a method
	// the stable bundle declares is stable, and a stable method needs no fallback
	// because there is no negotiation that can take it away. Only a method that
	// exists solely in the experimental bundle is experimental, and only those
	// carry a fallback.
	stableMethods := make(map[string]struct{}, len(stable.ClientRequests))
	for _, method := range stable.ClientRequests {
		stableMethods[method.Method] = struct{}{}
	}

	capabilities := make([]CapabilityContract, 0, len(exposed)+2)
	seen := make(map[string]struct{}, len(exposed))
	// The experimental bundle is a superset, but both are walked so that a method
	// present only in the stable bundle cannot be missed if that ever stops holding.
	for _, surface := range []ContractSurface{stable, experimental} {
		for _, method := range surface.ClientRequests {
			security, ok := exposed[method.Method]
			if !ok {
				continue
			}
			if _, duplicate := seen[method.Method]; duplicate {
				continue
			}
			seen[method.Method] = struct{}{}
			capability := CapabilityContract{
				ID:       CapabilityID("rpc:" + method.Method),
				Requires: []WireRequirement{{Kind: WireClientRequest, Method: method.Method}},
				Security: security,
			}
			if _, isStable := stableMethods[method.Method]; isStable {
				capability.Stability = StabilityStable
			} else {
				capability.Stability = StabilityExperimental
				capability.Fallback = fallbackForMethod(method.Method)
			}
			capabilities = append(capabilities, capability)
		}
	}
	capabilities = append(capabilities,
		CapabilityContract{ID: CapabilityThreadSource, Stability: StabilityStable, Requires: []WireRequirement{{Kind: WireClientRequest, Method: "thread/start"}, {Kind: WireClientRequest, Method: "thread/fork"}}, Security: SecurityWrite},
		CapabilityContract{ID: CapabilityThreadForkDeferGoal, Stability: StabilityExperimental, Requires: []WireRequirement{{Kind: WireClientRequest, Method: "thread/fork"}}, Security: SecurityWrite},
	)
	sort.Slice(capabilities, func(i, j int) bool { return capabilities[i].ID < capabilities[j].ID })
	return capabilities
}

func generatedFixtures(stable, experimental ContractSurface, stableDocs, experimentalDocs generatedSchemaDocs) []ContractFixture {
	fixtures := make([]ContractFixture, 0, len(experimental.ClientRequests)+len(experimental.ServerNotifications)+len(experimental.ServerRequests))
	seen := make(map[string]struct{})
	appendSurface := func(stability Stability, surface ContractSurface, docs generatedSchemaDocs) {
		for kind, entries := range map[WireKind][]WireContract{
			WireClientRequest: surface.ClientRequests, WireNotification: surface.ServerNotifications, WireServerRequest: surface.ServerRequests,
		} {
			for _, entry := range entries {
				key := string(kind) + "\x00" + entry.Method
				if _, ok := seen[key]; ok {
					continue
				}
				seen[key] = struct{}{}
				response := responseSchema(entry.Method, entry.Params, docs)
				if kind == WireNotification {
					response = "none"
				}
				fixtures = append(fixtures, ContractFixture{
					Kind: kind, Stability: stability, Method: entry.Method, ParamsSchema: entry.Params,
					ResponseSchema: response,
					RequiredParams: append([]string(nil), docs.definitions[entry.Params].Required...),
					RequiredResult: append([]string(nil), docs.definitions[response].Required...),
				})
			}
		}
	}
	appendSurface(StabilityStable, stable, stableDocs)
	appendSurface(StabilityExperimental, experimental, experimentalDocs)
	sort.Slice(fixtures, func(i, j int) bool {
		if fixtures[i].Kind == fixtures[j].Kind {
			return fixtures[i].Method < fixtures[j].Method
		}
		return fixtures[i].Kind < fixtures[j].Kind
	})
	return fixtures
}

func responseSchema(method, params string, docs generatedSchemaDocs) string {
	if strings.HasSuffix(params, "Params") {
		candidate := strings.TrimSuffix(params, "Params") + "Response"
		if _, ok := docs.definitions[candidate]; ok {
			return candidate
		}
	}
	overrides := map[string]string{
		"account/logout":                           "LogoutAccountResponse",
		"account/rateLimits/read":                  "GetAccountRateLimitsResponse",
		"account/usage/read":                       "GetAccountTokenUsageResponse",
		"account/workspaceMessages/read":           "GetWorkspaceMessagesResponse",
		"config/batchWrite":                        "ConfigWriteResponse",
		"config/mcpServer/reload":                  "McpServerRefreshResponse",
		"config/value/write":                       "ConfigWriteResponse",
		"configRequirements/read":                  "ConfigRequirementsReadResponse",
		"externalAgentConfig/import/readHistories": "ExternalAgentConfigImportHistoriesReadResponse",
		"memory/reset":                             "MemoryResetResponse",
		"remoteControl/disable":                    "RemoteControlDisableResponse",
		"remoteControl/enable":                     "RemoteControlEnableResponse",
		"remoteControl/status/read":                "RemoteControlStatusReadResponse",
		"windowsSandbox/readiness":                 "WindowsSandboxReadinessResponse",
	}
	if response := overrides[method]; response != "" {
		if _, ok := docs.definitions[response]; ok {
			return response
		}
	}
	return "typed"
}

func readStandaloneSchemas(t *testing.T, dir string) map[string]struct {
	Required []string `json:"required"`
} {
	t.Helper()
	out := make(map[string]struct {
		Required []string `json:"required"`
	})
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatal(err)
	}
	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".json" {
			continue
		}
		raw, err := os.ReadFile(filepath.Join(dir, entry.Name()))
		if err != nil {
			t.Fatal(err)
		}
		var schema struct {
			Title       string   `json:"title"`
			Required    []string `json:"required"`
			Definitions map[string]struct {
				Required []string `json:"required"`
			} `json:"definitions"`
		}
		if json.Unmarshal(raw, &schema) == nil && schema.Title != "" {
			out[schema.Title] = struct {
				Required []string `json:"required"`
			}{Required: schema.Required}
		}
		for name, definition := range schema.Definitions {
			if _, exists := out[name]; !exists {
				out[name] = definition
			}
		}
	}
	return out
}

func fallbackForMethod(method string) CapabilityID {
	switch method {
	case "thread/search":
		return CapabilityThreadList
	case "thread/searchOccurrences", "thread/turns/list", "thread/items/list":
		return CapabilityID("rpc:thread/read")
	case "thread/settings/update":
		return CapabilityID("rpc:turn/start")
	case "fuzzyFileSearch/sessionStart", "fuzzyFileSearch/sessionUpdate", "fuzzyFileSearch/sessionStop":
		return CapabilityID("rpc:fuzzyFileSearch")
	case "plugin/search":
		return CapabilityID("rpc:plugin/list")
	case "project/list", "project/read", "project/create", "project/import", "project/update", "project/move", "project/delete":
		return CapabilityThreadList
	default:
		return ""
	}
}

func securityForMethod(method string) SecurityClass {
	switch {
	case strings.Contains(method, "delete"), strings.Contains(method, "remove"), strings.Contains(method, "uninstall"), strings.Contains(method, "logout"):
		return SecurityDestructive
	case strings.Contains(method, "login"), strings.Contains(method, "oauth"), strings.Contains(method, "feedback"):
		return SecuritySecret
	case strings.HasPrefix(method, "command/"), strings.HasPrefix(method, "process/"), strings.Contains(method, "shellCommand"), strings.Contains(method, "backgroundTerminals"):
		return SecurityExecution
	case strings.Contains(method, "realtime"):
		return SecurityRealtime
	case strings.Contains(method, "/set"), strings.Contains(method, "/write"), strings.Contains(method, "/create"), strings.Contains(method, "/update"), strings.Contains(method, "/import"), strings.Contains(method, "/install"), strings.Contains(method, "/add"):
		return SecurityWrite
	default:
		return SecurityRead
	}
}

func sourceOnlyDelta(installedStable, installedExperimental, sourceStable, sourceExperimental ContractSurface) []string {
	var delta []string
	appendDelta := func(kind WireKind, installed, source []WireContract) {
		installedSet := make(map[string]struct{}, len(installed))
		for _, entry := range installed {
			installedSet[entry.Method] = struct{}{}
		}
		for _, entry := range source {
			if _, ok := installedSet[entry.Method]; !ok {
				delta = append(delta, string(kind)+":"+entry.Method)
			}
		}
	}
	appendDelta(WireClientRequest, installedExperimental.ClientRequests, sourceExperimental.ClientRequests)
	appendDelta(WireNotification, installedStable.ServerNotifications, sourceStable.ServerNotifications)
	sort.Strings(delta)
	return delta
}

func requiredEnv(t *testing.T, name string) string {
	t.Helper()
	value := os.Getenv(name)
	if value == "" {
		t.Fatalf("%s is required", name)
	}
	return value
}

func writeGeneratedJSON(t *testing.T, path string, value any) {
	t.Helper()
	raw, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	raw = append(raw, '\n')
	if err := os.WriteFile(path, raw, 0o644); err != nil {
		t.Fatal(err)
	}
	t.Logf("wrote %s (%d bytes)", path, len(raw))
}

func (d generatedSchemaDocs) String() string {
	return fmt.Sprintf("%d definitions", len(d.definitions))
}
